//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\WetTang\Src\WeiTang\install\application\TYCheckGap.cpp
//
//        This file was generated by the NX Block Styler
//        Created by: Administrator
//              Version: NX 7
//              Date: 07-28-2019  (Format: mm-dd-yyyy)
//              Time: 18:55 (Format: hh-mm)
//
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "TYCheckGap.hpp"
#include <uf_disp.h>
#include <uf_modl.h>
#include "../Common/Com.h"
#include "../Common/Com_UI.h"
#include "../Common/Com_UG.h"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(TYCheckGap::theSession) = NULL;
UI *(TYCheckGap::theUI) = NULL;

//------------------------------------------------------------------------------
// Declaration of global variables
//------------------------------------------------------------------------------
TYCheckGap *theTYCheckGap;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
TYCheckGap::TYCheckGap()
{
	try
	{
		// Initialize the NX Open C++ API environment
		TYCheckGap::theSession = NXOpen::Session::GetSession();
		TYCheckGap::theUI = UI::GetUI();
		theDialogName = "TYCheckGap.dlx";
		theDialog = TYCheckGap::theUI->CreateDialog(theDialogName.c_str());
		// Registration of callback functions
		theDialog->AddApplyHandler(make_callback(this, &TYCheckGap::apply_cb));
		theDialog->AddOkHandler(make_callback(this, &TYCheckGap::ok_cb));
		theDialog->AddUpdateHandler(make_callback(this, &TYCheckGap::update_cb));
		theDialog->AddCancelHandler(make_callback(this, &TYCheckGap::cancel_cb));
		theDialog->AddFilterHandler(make_callback(this, &TYCheckGap::filter_cb));
		theDialog->AddInitializeHandler(make_callback(this, &TYCheckGap::initialize_cb));
		theDialog->AddDialogShownHandler(make_callback(this, &TYCheckGap::dialogShown_cb));
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		throw;
	}
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
TYCheckGap::~TYCheckGap()
{
	if (theDialog != NULL)
	{
		delete theDialog;
		theDialog = NULL;
	}
}

int TYCheckGap::Show()
{
	try
	{
		theDialog->Show();
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return 0;
}


//------------------------------------------------------------------------------
//Method name: Show_TYCheckGap
//------------------------------------------------------------------------------
void TYCheckGap::Show_TYCheckGap()
{
	try
	{
		theTYCheckGap = new TYCheckGap();
		// The following method shows the dialog immediately
		theTYCheckGap->Show();
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	delete theTYCheckGap;
}

//------------------------------------------------------------------------------
//---------------------Block Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void TYCheckGap::initialize_cb()
{
	try
	{
		groupSelectBodies = theDialog->TopBlock()->FindBlock("groupSelectBodies");
		selectionBasePlate = theDialog->TopBlock()->FindBlock("selectionBasePlate");
		selectionBodies = theDialog->TopBlock()->FindBlock("selectionBodies");

		UI_SetSeletSolidBody(selectionBasePlate);
		UI_SetSeletSolidBody(selectionBodies);

		for(int i = 0; i < m_gapBodies.size(); i++)
		{
			UF_DISP_set_highlight(m_gapBodies[i],1);
		}
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void TYCheckGap::dialogShown_cb()
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
}

static int CheckOneBody(tag_t diban, tag_t body, double &dis)
{
	int ret = TYCOM_AskMinimumDist(diban, body, dis);
	return 0;
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int TYCheckGap::apply_cb()
{
	try
	{
		m_gapBodies.clear();
		std::vector<NXOpen::TaggedObject *> dibans = UI_GetSelectObjects(selectionBasePlate);
		tag_t diban = dibans[0]->Tag();

		std::vector<NXOpen::TaggedObject *> pbodies = UI_GetSelectObjects(selectionBodies);
		vtag_t bodies;
		for(int i = 0; i < pbodies.size(); i++)
			bodies.push_back(pbodies[i]->Tag()); 

		//
		double dis = 0;
		int num = 0;
		for(int i = 0; i < bodies.size(); i++)
		{
			CheckOneBody(diban, bodies[i], dis);
			if(dis > TY_GAP_DIS)
			{
				m_gapBodies.push_back(bodies[i]);
			}
		}


		//Report
		logical response = 0;
		UF_UI_is_listing_window_open(&response);
		if(!response)
			UF_UI_open_listing_window();

		//UF_UI_write_listing_window("-----------------若宇称重报告-------------------\n\n\n");
		char str[1024]="";
		sprintf(str, "共选择%d个检测实体\n其中%d个是悬空状态,系统已经高亮显示\n",bodies.size(),m_gapBodies.size());
		UF_UI_write_listing_window(str);
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return 0;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int TYCheckGap::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
	try
	{
		if(block == selectionBasePlate)
		{
			//---------Enter your code here-----------
		}
		else if(block == selectionBodies)
		{
			//---------Enter your code here-----------
		}
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int TYCheckGap::ok_cb()
{
	try
	{
		apply_cb();
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return 0;
}

//------------------------------------------------------------------------------
//Callback Name: cancel_Cb
//------------------------------------------------------------------------------
int TYCheckGap::cancel_cb()
{
	try
	{
		//---- Enter your callback code here -----
	}
	catch(exception& ex)
	{
		//---- Enter your exception handling code here -----
		TYCheckGap::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
	}
	return 0;
}

//------------------------------------------------------------------------------
//Callback Name: filter_cb
//------------------------------------------------------------------------------
int TYCheckGap::filter_cb(NXOpen::BlockStyler::UIBlock*  block, NXOpen::TaggedObject* selectObject)
{
	return(UF_UI_SEL_ACCEPT);
}
