//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\WetTang\Src\WeiTang\install\application\TYMirrorText.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Administrator
//              Version: NX 7
//              Date: 07-28-2019  (Format: mm-dd-yyyy)
//              Time: 18:56
//
//==============================================================================

#ifndef TYMIRRORTEXT_H_INCLUDED
#define TYMIRRORTEXT_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include "../Common/TY_Def.h"
#include <uf_cfi_types.h>

//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);
#define                 SnapPointTypesEnabled_Inferred (1 << 1);
#define           SnapPointTypesEnabled_ScreenPosition (1 << 2);
#define                 SnapPointTypesEnabled_EndPoint (1 << 3);
#define                 SnapPointTypesEnabled_MidPoint (1 << 4);
#define             SnapPointTypesEnabled_ControlPoint (1 << 5);
#define             SnapPointTypesEnabled_Intersection (1 << 6);
#define                SnapPointTypesEnabled_ArcCenter (1 << 7);
#define            SnapPointTypesEnabled_QuadrantPoint (1 << 8);
#define            SnapPointTypesEnabled_ExistingPoint (1 << 9);
#define             SnapPointTypesEnabled_PointonCurve (1 <<10);
#define           SnapPointTypesEnabled_PointonSurface (1 <<11);
#define         SnapPointTypesEnabled_PointConstructor (1 <<12);
#define     SnapPointTypesEnabled_TwocurveIntersection (1 <<13);
#define             SnapPointTypesEnabled_TangentPoint (1 <<14);
#define                    SnapPointTypesEnabled_Poles (1 <<15);
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define          SnapPointTypesOnByDefault_UserDefined (1 << 0);
#define             SnapPointTypesOnByDefault_Inferred (1 << 1);
#define       SnapPointTypesOnByDefault_ScreenPosition (1 << 2);
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define SnapPointTypesOnByDefault_TwocurveIntersection (1 <<13);
#define         SnapPointTypesOnByDefault_TangentPoint (1 <<14);
#define                SnapPointTypesOnByDefault_Poles (1 <<15);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Forward declaration for Class
//------------------------------------------------------------------------------
class TYText;
//
//------------------------------------------------------------------------------
// Declaration of global variables
//------------------------------------------------------------------------------

class TYText
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    TYText();
    ~TYText();
    int Show();

	int UpdateShowStatus();
	int AddTextToModelReference(vtag_t &oriSplines, tag_t body);
	int ReplaceTexts();
	int GetKeyText(tag_t group, vtag_t &texts);
	int ImportText(tag_t &group, NXOpen::Point3d pntOri,NXOpen::Point3d pntX, NXOpen::Point3d pntY);
	int GetPrtFileName(char prtFileName[UF_CFI_MAX_PATH_NAME_SIZE]);
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementaiton
    // of these prototypes is provided in the TYMirrorText.cpp file. 
    // You are REQUIRED to write the implementation for these funtions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int cancel_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock*  block, NXOpen::TaggedObject* selectObject);
    
private:
    std::string theDialogName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::UIBlock* groupTextType;// Block type: Group
    NXOpen::BlockStyler::UIBlock* enumTextType;// Block type: Enumeration
    NXOpen::BlockStyler::UIBlock* groupContents;// Block type: Group
    NXOpen::BlockStyler::UIBlock* stringText1;// Block type: String
    NXOpen::BlockStyler::UIBlock* stringText2;// Block type: String
    NXOpen::BlockStyler::UIBlock* stringText3;// Block type: String
    NXOpen::BlockStyler::UIBlock* stringText4;// Block type: String
    NXOpen::BlockStyler::UIBlock* stringText5;// Block type: String
    NXOpen::BlockStyler::UIBlock* stringText6;// Block type: String
    NXOpen::BlockStyler::UIBlock* stringText7;// Block type: String
    NXOpen::BlockStyler::UIBlock* stringText8;// Block type: String
    NXOpen::BlockStyler::UIBlock* groupPosition;// Block type: Group
    NXOpen::BlockStyler::UIBlock* selectionBody;// Block type: Selection
    NXOpen::BlockStyler::UIBlock* enumEdgePos;// Block type: Enumeration
    NXOpen::BlockStyler::UIBlock* pointOrigin;// Block type: Specify Point
    NXOpen::BlockStyler::UIBlock* pointX;// Block type: Specify Point
    NXOpen::BlockStyler::UIBlock* pointY;// Block type: Specify Point
	NXOpen::BlockStyler::UIBlock* toggleMirror;// Block type: Toggle
	NXOpen::BlockStyler::UIBlock* mirrorPlane;// Block type: Specify Plane
    NXOpen::BlockStyler::UIBlock* groupSetting;// Block type: Group
    NXOpen::BlockStyler::UIBlock* doubleTextHeight;// Block type: Double
    NXOpen::BlockStyler::UIBlock* doubleEdgeDist;// Block type: Double

	tag_t m_text1;//ATTR_TYCOM_KEZI_1
	tag_t m_text2;//ATTR_TYCOM_KEZI_2
	tag_t m_text3;//ATTR_TYCOM_KEZI_3
	tag_t m_text4;//ATTR_TYCOM_KEZI_4
	tag_t m_text5;//ATTR_TYCOM_KEZI_5
	tag_t m_text6;//ATTR_TYCOM_KEZI_6
	tag_t m_text7;//ATTR_TYCOM_KEZI_7
	tag_t m_text8;//ATTR_TYCOM_KEZI_8
    
};

void TYText_Main();
#endif //TYMIRRORTEXT_H_INCLUDED
